version: '3'
services:
  tussdashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "420:3000"
    volumes:
      - .:/app
      - ./assets:/app/assets
      - ./components:/app/components
      - ./layouts:/app/layouts
      - ./pages:/app/pages
      - ./plugins:/app/plugins
      - ./static:/app/static
      - ./store:/app/store
      - ./types:/app/types

  tussapi:
    build:
      context: ./tuss-back
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - ./tuss-back:/app
      - ./tuss-back/node_modules:/app/node_modules
    

  mongodb:
    image: mongo
    ports:
      - '${MONGO_DB_PORT}:${MONGO_DB_PORT}'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - database:/data/db


  mongo_express:
    image: mongo-express:latest
    ports:
      - '421:8081'
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${MONGO_DB_PORT}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  database:
