version: '3'
services:
  tussdashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - ./assets:/app/assets
      - ./components:/app/components
      - ./layouts:/app/layouts
      - ./pages:/app/pages
      - ./plugins:/app/plugins
      - ./static:/app/static
      - ./store:/app/store
      - ./types:/app/types