export enum ERifleTypes {
  aeg = 'aeg',
  gbb = 'gbb',
  spring = 'spring',
  hpa = 'hpa',
  co2 = 'co2',
  bolt = 'bolt',
  sniper = 'sniper',
  shotgun = 'shotgun',
  grenade = 'grenade',
  mine = 'mine',
  grenadeLauncher = 'grenadeLauncher',
  rocketLauncher = 'rocketLauncher',
  mortar = 'mortar',
  pistol = 'pistol',
  revolver = 'revolver',
  smg = 'smg',
  lmg = 'lmg',
  dmr = 'dmr',
}